### ISSUE TITLE
大佬 您好 我想复现您的项目 请问一下您使用的数据集是什么？

### ISSUE THREAD

**Issue by zhengxinvip** [TWSFar/DSSD#1]

**Comment by zhengxinvip** [comment]
> No description provided.

已解决

**Comment by TWSFar** [comment]
你好，我使用的就是voc2012， 这个项目是我练习pytorch而搭建的，精准度很低（一般为AP70+， 我跑最高是52），最近比较忙就没有修改其中的问题，可能存在一些bug， 改进的话你可以尝试修改损失。


| |
段成真
|
|
twsfcz@163.com
|
签名由网易邮箱大师定制
在2019年9月16日 10:45，zhengxinvip<notifications@github.com> 写道：
